### ISSUE TITLE
Multivariate temperature analysis

### ISSUE THREAD

**Issue by jrcunning** [hputnam/Moorea_Sym#8]
Explore metrics of interest and run multivariate analyses

**Comment by daniclaar** [comment]
I have been thinking about this quite a lot, and I am a little bit worried about creating a composite variable based on mathematically-nonindependent variables (e.g. variance and standard deviation, but broadly true for these calculated variables). So I did a simple t-test on each variable (not the most elegant approach, I know, but I wanted  to see which variables were different between the "high" and "low" variability sites) The only variables that were significantly different were `variance` and `sd`. This makes me wonder if we really do need to create a potentially problematic composite variable, or if we can just use `sd` or `var` as a predictor. Especially since variability is the main question we are trying to answer at this point. Thoughts?
